// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhsjjvjrvnqssthprtma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoc2pqdmpydm5xc3N0aHBydG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMTI1MTgsImV4cCI6MjA1NTc4ODUxOH0.otqSY904Zth2kuwbh55hY1H4Nqk83HaE6lGHiuSuVrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);